
package cz.gpe.pay.pay_ws.proc.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-02-12T09:56:14.564+01:00
 * Generated source version: 4.0.2
 */

@WebFault(name = "cardOnFilePaymentServiceException", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
public class CardOnFilePaymentServiceException extends Exception {

    private cz.gpe.pay.pay_ws.proc.v1.type.CardOnFilePaymentFaultDetail faultInfo;

    public CardOnFilePaymentServiceException() {
        super();
    }

    public CardOnFilePaymentServiceException(String message) {
        super(message);
    }

    public CardOnFilePaymentServiceException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CardOnFilePaymentServiceException(String message, cz.gpe.pay.pay_ws.proc.v1.type.CardOnFilePaymentFaultDetail cardOnFilePaymentServiceException) {
        super(message);
        this.faultInfo = cardOnFilePaymentServiceException;
    }

    public CardOnFilePaymentServiceException(String message, cz.gpe.pay.pay_ws.proc.v1.type.CardOnFilePaymentFaultDetail cardOnFilePaymentServiceException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = cardOnFilePaymentServiceException;
    }

    public cz.gpe.pay.pay_ws.proc.v1.type.CardOnFilePaymentFaultDetail getFaultInfo() {
        return this.faultInfo;
    }
}
