
package cz.gpe.pay.pay_ws.proc.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-02-12T09:56:14.557+01:00
 * Generated source version: 4.0.2
 */

@WebFault(name = "echoServiceException", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
public class EchoServiceException extends Exception {

    private cz.gpe.pay.pay_ws.proc.v1.type.EchoFaultDetail faultInfo;

    public EchoServiceException() {
        super();
    }

    public EchoServiceException(String message) {
        super(message);
    }

    public EchoServiceException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EchoServiceException(String message, cz.gpe.pay.pay_ws.proc.v1.type.EchoFaultDetail echoServiceException) {
        super(message);
        this.faultInfo = echoServiceException;
    }

    public EchoServiceException(String message, cz.gpe.pay.pay_ws.proc.v1.type.EchoFaultDetail echoServiceException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = echoServiceException;
    }

    public cz.gpe.pay.pay_ws.proc.v1.type.EchoFaultDetail getFaultInfo() {
        return this.faultInfo;
    }
}
