package cz.gpe.pay.pay_ws.proc.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-02-12T09:56:14.600+01:00
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "PaymentService",
                  wsdlLocation = "file:/C:/Users/lejce/Desktop/GitHub/external/wsdl/cws_v1.wsdl",
                  targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
public class PaymentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gpe.cz/pay/pay-ws/proc/v1", "PaymentService");
    public final static QName PaymentPortV1 = new QName("http://gpe.cz/pay/pay-ws/proc/v1", "PaymentPortV1");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/lejce/Desktop/GitHub/external/wsdl/cws_v1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PaymentService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/lejce/Desktop/GitHub/external/wsdl/cws_v1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PaymentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PaymentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PaymentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PaymentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PaymentPort
     */
    @WebEndpoint(name = "PaymentPortV1")
    public PaymentPort getPaymentPortV1() {
        return super.getPort(PaymentPortV1, PaymentPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentPort
     */
    @WebEndpoint(name = "PaymentPortV1")
    public PaymentPort getPaymentPortV1(WebServiceFeature... features) {
        return super.getPort(PaymentPortV1, PaymentPort.class, features);
    }

}
