
package cz.gpe.pay.pay_ws.proc.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-02-12T09:56:14.490+01:00
 * Generated source version: 4.0.2
 */

@WebFault(name = "paymentServiceException", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
public class PaymentServiceException extends Exception {

    private cz.gpe.pay.pay_ws.proc.v1.type.PaymentFaultDetail faultInfo;

    public PaymentServiceException() {
        super();
    }

    public PaymentServiceException(String message) {
        super(message);
    }

    public PaymentServiceException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PaymentServiceException(String message, cz.gpe.pay.pay_ws.proc.v1.type.PaymentFaultDetail paymentServiceException) {
        super(message);
        this.faultInfo = paymentServiceException;
    }

    public PaymentServiceException(String message, cz.gpe.pay.pay_ws.proc.v1.type.PaymentFaultDetail paymentServiceException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = paymentServiceException;
    }

    public cz.gpe.pay.pay_ws.proc.v1.type.PaymentFaultDetail getFaultInfo() {
        return this.faultInfo;
    }
}
