package cz.gpe.pay.pay_ws.proc.v1;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-02-12T09:56:14.572+01:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", name = "PaymentPort")
@XmlSeeAlso({cz.gpe.gpwebpay.additionalinfo.response.v1.ObjectFactory.class, cz.gpe.pay.pay_ws.proc.v1.type.ObjectFactory.class, ObjectFactory.class})
public interface PaymentPort {

    @WebMethod
    @RequestWrapper(localName = "processPayoutWinning", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPayoutWinning")
    @ResponseWrapper(localName = "processPayoutWinningResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPayoutWinningResponse")
    @WebResult(name = "payoutWinningResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PayoutWinningResponse processPayoutWinning(

        @WebParam(name = "payoutWinningRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PayoutWinningRequest payoutWinningRequest
    ) throws PaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "revokePaymentLink", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.RevokePaymentLink")
    @ResponseWrapper(localName = "revokePaymentLinkResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.RevokePaymentLinkResponse")
    @WebResult(name = "revokePaymentLinkResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.RevokePaymentLinkResponse revokePaymentLink(

        @WebParam(name = "revokePaymentLinkRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentStatusRequest revokePaymentLinkRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processPayout", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPayout")
    @ResponseWrapper(localName = "processPayoutResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPayoutResponse")
    @WebResult(name = "payoutResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PayoutResponse processPayout(

        @WebParam(name = "payoutRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PayoutRequest payoutRequest
    ) throws PaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "processPayoutInsurance", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPayoutInsurance")
    @ResponseWrapper(localName = "processPayoutInsuranceResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPayoutInsuranceResponse")
    @WebResult(name = "payoutInsuranceResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PayoutInsuranceResponse processPayoutInsurance(

        @WebParam(name = "payoutInsuranceRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PayoutInsuranceRequest payoutInsuranceRequest
    ) throws PaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "processBatchClose", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessBatchClose")
    @ResponseWrapper(localName = "processBatchCloseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessBatchCloseResponse")
    @WebResult(name = "batchCloseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.BatchCloseResponse processBatchClose(

        @WebParam(name = "batchClose", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.BatchCloseRequest batchClose
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processPaymentClose", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPaymentClose")
    @ResponseWrapper(localName = "processPaymentCloseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPaymentCloseResponse")
    @WebResult(name = "paymentCloseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PaymentCloseResponse processPaymentClose(

        @WebParam(name = "paymentCloseRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentCloseRequest paymentCloseRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processUsageBasedSubscriptionPayment", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessUsageBasedSubscriptionPayment")
    @ResponseWrapper(localName = "processUsageBasedSubscriptionPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessUsageBasedSubscriptionPaymentResponse")
    @WebResult(name = "usageBasedSubscriptionPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.UsageBasedSubscriptionPaymentResponse processUsageBasedSubscriptionPayment(

        @WebParam(name = "usageBasedSubscriptionPaymentRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.UsageBasedSubscriptionPaymentRequest usageBasedSubscriptionPaymentRequest
    ) throws PaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "processCaptureReverse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessCaptureReverse")
    @ResponseWrapper(localName = "processCaptureReverseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessCaptureReverseResponse")
    @WebResult(name = "captureReverseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.CaptureReverseResponse processCaptureReverse(

        @WebParam(name = "captureReverseRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.CaptureReverseRequest captureReverseRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processRefundReverse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessRefundReverse")
    @ResponseWrapper(localName = "processRefundReverseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessRefundReverseResponse")
    @WebResult(name = "refundReverseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.RefundReverseResponse processRefundReverse(

        @WebParam(name = "refundReverseRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.RefundReverseRequest refundReverseRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "getPaymentLinkStatus", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetPaymentLinkStatus")
    @ResponseWrapper(localName = "getPaymentLinkStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetPaymentLinkStatusResponse")
    @WebResult(name = "paymentLinkStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PaymentLinkStatusResponse getPaymentLinkStatus(

        @WebParam(name = "paymentLinkStatusRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentLinkStatusRequest paymentLinkStatusRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processTokenPayment", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessTokenPayment")
    @ResponseWrapper(localName = "processTokenPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessTokenPaymentResponse")
    @WebResult(name = "tokenPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.TokenPaymentResponse processTokenPayment(

        @WebParam(name = "tokenPaymentRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.TokenPaymentRequest tokenPaymentRequest
    ) throws PaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "getPaymentStatus", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetPaymentStatus")
    @ResponseWrapper(localName = "getPaymentStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetPaymentStatusResponse")
    @WebResult(name = "paymentStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PaymentStatusResponse getPaymentStatus(

        @WebParam(name = "paymentStatusRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentStatusRequest paymentStatusRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "getMasterPaymentStatus", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetMasterPaymentStatus")
    @ResponseWrapper(localName = "getMasterPaymentStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetMasterPaymentStatusResponse")
    @WebResult(name = "masterPaymentStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.MasterPaymentStatusResponse getMasterPaymentStatus(

        @WebParam(name = "masterPaymentStatusRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentStatusRequest masterPaymentStatusRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "getCardData", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetCardData")
    @ResponseWrapper(localName = "getCardDataResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetCardDataResponse")
    @WebResult(name = "cardDataResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.CardDataResponse getCardData(

        @WebParam(name = "cardDataRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.CardDataRequest cardDataRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "getPaymentDetail", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetPaymentDetail")
    @ResponseWrapper(localName = "getPaymentDetailResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetPaymentDetailResponse")
    @WebResult(name = "paymentDetailResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PaymentDetailResponse getPaymentDetail(

        @WebParam(name = "paymentDetailRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentStatusRequest paymentDetailRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "resolvePaymentStatus", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ResolvePaymentStatus")
    @ResponseWrapper(localName = "resolvePaymentStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ResolvePaymentStatusResponse")
    @WebResult(name = "paymentStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PaymentStatusResponse resolvePaymentStatus(

        @WebParam(name = "resolvePaymentStatusRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.ResolvePaymentStatusRequest resolvePaymentStatusRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processTokenRevoke", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessTokenRevoke")
    @ResponseWrapper(localName = "processTokenRevokeResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessTokenRevokeResponse")
    @WebResult(name = "tokenRevokeResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.TokenRevokeResponse processTokenRevoke(

        @WebParam(name = "tokenRevokeRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.TokenRevokeRequest tokenRevokeRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "createPaymentLink", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.CreatePaymentLink")
    @ResponseWrapper(localName = "createPaymentLinkResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.CreatePaymentLinkResponse")
    @WebResult(name = "paymentLinkResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PaymentLinkResponse createPaymentLink(

        @WebParam(name = "paymentLinkRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentLinkRequest paymentLinkRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "echo", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.EchoResponse")
    public void echo()
 throws EchoServiceException;

    @WebMethod
    @RequestWrapper(localName = "processCapture", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessCapture")
    @ResponseWrapper(localName = "processCaptureResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessCaptureResponse")
    @WebResult(name = "captureResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.CaptureResponse processCapture(

        @WebParam(name = "captureRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.CaptureRequest captureRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "mpsPreCheckout", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.MpsPreCheckout")
    @ResponseWrapper(localName = "mpsPreCheckoutResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.MpsPreCheckoutResponse")
    @WebResult(name = "mpsPreCheckoutResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.MpsPreCheckoutResponse mpsPreCheckout(

        @WebParam(name = "mpsPreCheckoutRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.MpsPreCheckoutRequest mpsPreCheckoutRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "getTokenStatus", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetTokenStatus")
    @ResponseWrapper(localName = "getTokenStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetTokenStatusResponse")
    @WebResult(name = "tokenStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.TokenStatusResponse getTokenStatus(

        @WebParam(name = "tokenStatusRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.TokenStatusRequest tokenStatusRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processCardOnFilePayment", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessCardOnFilePayment")
    @ResponseWrapper(localName = "processCardOnFilePaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessCardOnFilePaymentResponse")
    @WebResult(name = "cardOnFilePaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.CardOnFilePaymentResponse processCardOnFilePayment(

        @WebParam(name = "cardOnFilePaymentRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.CardOnFilePaymentRequest cardOnFilePaymentRequest
    ) throws CardOnFilePaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "processPaymentDelete", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPaymentDelete")
    @ResponseWrapper(localName = "processPaymentDeleteResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPaymentDeleteResponse")
    @WebResult(name = "paymentDeleteResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PaymentDeleteResponse processPaymentDelete(

        @WebParam(name = "paymentDeleteRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentDeleteRequest paymentDeleteRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processMasterPaymentRevoke", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessMasterPaymentRevoke")
    @ResponseWrapper(localName = "processMasterPaymentRevokeResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessMasterPaymentRevokeResponse")
    @WebResult(name = "masterPaymentStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.MasterPaymentStatusResponse processMasterPaymentRevoke(

        @WebParam(name = "masterPaymentStatusRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PaymentStatusRequest masterPaymentStatusRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processRefund", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessRefund")
    @ResponseWrapper(localName = "processRefundResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessRefundResponse")
    @WebResult(name = "refundRequestResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.RefundResponse processRefund(

        @WebParam(name = "refundRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.RefundRequest refundRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processPrepaidPayment", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPrepaidPayment")
    @ResponseWrapper(localName = "processPrepaidPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessPrepaidPaymentResponse")
    @WebResult(name = "prepaidPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.PrepaidPaymentResponse processPrepaidPayment(

        @WebParam(name = "prepaidPaymentRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.PrepaidPaymentRequest prepaidPaymentRequest
    ) throws PaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "processRegularSubscriptionPayment", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessRegularSubscriptionPayment")
    @ResponseWrapper(localName = "processRegularSubscriptionPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessRegularSubscriptionPaymentResponse")
    @WebResult(name = "regularSubscriptionPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.RegularSubscriptionPaymentResponse processRegularSubscriptionPayment(

        @WebParam(name = "regularSubscriptionPaymentRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.RegularSubscriptionPaymentRequest regularSubscriptionPaymentRequest
    ) throws PaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "processAuthorizationReverse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessAuthorizationReverse")
    @ResponseWrapper(localName = "processAuthorizationReverseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessAuthorizationReverseResponse")
    @WebResult(name = "authorizationReverseResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.AuthorizationReverseResponse processAuthorizationReverse(

        @WebParam(name = "authorizationReverseRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.AuthorizationReverseRequest authorizationReverseRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "mpsExpressCheckout", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.MpsExpressCheckout")
    @ResponseWrapper(localName = "mpsExpressCheckoutResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.MpsExpressCheckoutResponse")
    @WebResult(name = "mpsExpressCheckoutResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.MpsExpressCheckoutResponse mpsExpressCheckout(

        @WebParam(name = "mpsExpressCheckoutRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.MpsExpressCheckoutRequest mpsExpressCheckoutRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processUsageBasedPayment", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessUsageBasedPayment")
    @ResponseWrapper(localName = "processUsageBasedPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessUsageBasedPaymentResponse")
    @WebResult(name = "usageBasedPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.UsageBasedPaymentResponse processUsageBasedPayment(

        @WebParam(name = "usageBasedPaymentRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.CardOnFilePaymentRequest usageBasedPaymentRequest
    ) throws PaymentServiceException;

    @WebMethod
    @RequestWrapper(localName = "getSubsqTransBatchStatus", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetSubsqTransBatchStatus")
    @ResponseWrapper(localName = "getSubsqTransBatchStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.GetSubsqTransBatchStatusResponse")
    @WebResult(name = "subsqTransBatchStatusResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.SubsqTransBatchStatusResponse getSubsqTransBatchStatus(

        @WebParam(name = "subsqTransBatchStatusRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.SubsqTransBatchStatusRequest subsqTransBatchStatusRequest
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "processRecurringPayment", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessRecurringPayment")
    @ResponseWrapper(localName = "processRecurringPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1", className = "cz.gpe.pay.pay_ws.proc.v1.ProcessRecurringPaymentResponse")
    @WebResult(name = "recurringPaymentResponse", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
    public cz.gpe.pay.pay_ws.proc.v1.type.RecurringPaymentResponse processRecurringPayment(

        @WebParam(name = "recurringPaymentRequest", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
        cz.gpe.pay.pay_ws.proc.v1.type.RecurringPaymentRequest recurringPaymentRequest
    ) throws PaymentServiceException;
}
