
package cz.gpe.pay.pay_ws.proc.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * 2024-02-12T09:56:14.549+01:00
 * Generated source version: 4.0.2
 */

@WebFault(name = "serviceException", targetNamespace = "http://gpe.cz/pay/pay-ws/proc/v1")
public class ServiceException extends Exception {

    private cz.gpe.pay.pay_ws.proc.v1.type.FaultDetail faultInfo;

    public ServiceException() {
        super();
    }

    public ServiceException(String message) {
        super(message);
    }

    public ServiceException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, cz.gpe.pay.pay_ws.proc.v1.type.FaultDetail serviceException) {
        super(message);
        this.faultInfo = serviceException;
    }

    public ServiceException(String message, cz.gpe.pay.pay_ws.proc.v1.type.FaultDetail serviceException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = serviceException;
    }

    public cz.gpe.pay.pay_ws.proc.v1.type.FaultDetail getFaultInfo() {
        return this.faultInfo;
    }
}
